project:
  output-dir: docs
  type: website
  render:
    - "*.qmd"
    - "!Manuscript/"

exclude: ["*.rds","*.tex","*.csl","*.bib","docs*","404.html","_old*","_freeze*"]


website:
  title: "Mary Gorman"
  repo-url: https://github.com/MaryGorman/MaryGorman.github.io/
  site-url: https://marygorman.github.io/
  navbar:
    pinned: true
    search: true
    left:
      - text: Wing Family Tree
        file: WingTree.qmd
      - text: Games
        file: MomGames.qmd
      - text: Misc
        file: MiscMom.qmd
      
      

format:
  html:
    theme:
      light: Lumen
      dark: Slate
    css: ["Style/style1.css"]
    toc: true
    toc-location: right
    smooth-scroll: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.marygorman.github.io\.com\/custom'

execute:
  freeze: true  # never re-render during project render



    
      
# format:
#   html:
#     theme:
#       light: Style/embers.scss
#       dark: darkly
#     css: ["Style/style1.css"]
#     toc: true
#     toc-location: left
#     bibliography: /Users/thomasgorman/.pandoc/My_Library.bib
#     csl: Style/apa7_spacing.csl

    
